name:                prototype-D
version:             0.1.0.0
github:              "kirisaki/prototype-D"
license:             BSD3
author:              "Akihito KIRISAKI"
maintainer:          "kirisaki@klaraworks.net"
copyright:           "Akihito KIRISAKI"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kirisaki/prototype-D#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec

library:
  source-dirs: src

executables:
  prototype-D-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prototype-D

tests:
  prototype-D-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - prototype-D
